FROM python:3.12-slim
WORKDIR /app

# Crée un répertoire pour stocker le cache pip (re-build images faster)
RUN mkdir -p /root/.cache/pip

COPY api/requirements-api.txt .
# RUN pip install --no-cache-dir -r requirements-api.txt
RUN pip install -r requirements-api.txt --cache-dir=/root/.cache/pip

# sub-modules imports needs this architecture for the api code (dev)
COPY api/ /app/api/

# date_randomseed sub module
COPY src/bank_footfall/date_randomseed/ /app/bank_footfall/date_randomseed/

# for the agencies names and counters database
COPY data/data_base/ /app/data/data_base/

# COPY not need if use docker-compose but needed if direct use dockerfile (GCP)
CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
